name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test: 
    runs-on: ubuntu-latest
    name: Test & Checks
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1.18.2
        with:
          elixir-version: '1.17.3'
          otp-version: '27.1.2'
      - run: mix deps.get
      - run: mix format --check-formatted        
      - run: mix credo --strict
      - run: mix dialyzer
      - uses: actions/checkout@v4
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1     
      - run: mix deps.get
      - run: mix ecto.migrate
      - run: mix test
  build:
    if: github.ref == 'refs/heads/main'
    name: Build and deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ex-webhook:${{ github.sha }}